config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  
  
  resources :categories
  resources :posts, except: [:destroy] do
      resources :comments
      end

end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :post_categories
    has_many :posts, through: :post_categories
    validates :name, presence: true

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
    
    validates :body, presence: true

end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user, foreign_key: :user_id
    has_many :comments, foreign_key: :post_id 
    has_many :post_categories
    has_many :categories, through: :post_categories

    validates :title, presence: true
    validates :description, presence: true

end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
    belongs_to :post
    belongs_to :category

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :posts
    has_many :comments
    has_secure_password validations: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    
  
  def show
      @category = Category.find(params[:id])
  end
  
  def new
      @category = Category.new
      end
  
  def create
      @category = Category.new(category_params)
      if @category.save
             flash[:notice]= "Successful new Category"
          redirect_to posts_path
      else
        render :new
      end
    end
  
private

def category_params
    params.require(:category).permit(:name)
end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
      
      def create

      @post = Post.find(params[:post_id])
      @comment = @post.comments.new(params.require(:comment).permit(:body))
   if @comment.save
          flash[:notice]= "Successful new Comment"
          redirect_to post_path(@post)
      else
        render 'posts/show'
      end
      end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:show, :edit, :update]
    
  
  def index
       @post=Post.all
      end

  end
  
  def show
      @comment=Comment.new
  end
  
  def new
      @post=Post.new
      end
  
  def create
      @post=Post.new(post_params)
      @post.user_id = 1
      
      if @post.save
          flash[:notice]= "Successful new Post"
          redirect_to posts_path
      else
          render :new
      end
      end
  
  
  def edit
  end
  
  def update
       @post = Post.update(params[:id], post_params)
       if @post.save
          flash[:notice] = "Successful updated Post"
          redirect_to posts_path
      else
          render :edit
      end
      end

  
private

def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])

end

def set_post
    @post = Post.find(params[:id])
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<br>
<%= form_for @category do |f| %>


<div class='well'>

  <div class='control-group'>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
 </div>


  <%= f.submit 'Submit Category', class: 'btn btn-primary' %>
<% end %>


<br>

app/views/categories/new.html.erb
<h4>New Oracle Retail Categories</h4>

<%= render 'form' %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
  <li>
    <%= link_to 'New Post', new_post_path  %>
  </li>
  <li>
    <%= link_to 'New Category', new_category_path  %>
  </li>

</ul 

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
  <%=image_tag("Logic_Logo_Green.png")%>

    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        <%= render "shared/footer" %>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>



<div class='well'>
<%= form_for @post do |f| %>

  <div class='control-group'>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class='control-group'>
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class='control-group'>
    <%= f.label :description %>
    <%= f.text_area :description, rows: 8, class: 'span8' %>
  </div>
   <div class='control-group'>
    <%= f.label "Categories" %>
   <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
   <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
  <% end %>
  </div>

  <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post',  class: 'btn btn-primary') %>
<% end %>
</div>

app/views/posts/edit.html.erb
<h4>Edit Oracle Retail Posts</h4>

<%= render 'form' %>

app/views/posts/index.html.erb
<h4>Showing all Posts</h4>

<% @post.each do |post| %>
        <div class='row'>
                <div class='span8 well'>
                        <% post.categories.each do |category| %>
                              <div class = 'badge'>
                                <%=  "#{category.name}" %>
                            </div>
                        <% end %>

                        <p class = 'pull-right'>[<%= link_to 'edit this post', edit_post_path(post)%>]
                        </p>

                        <h4><p><%= post.title %></p> </h4>
                        <h5><a href= "http://<%="#{post.url}"%>"> <%="#{post.url}"%> </a></h5>


                        <hr>

                        <p><%= post.description %></p>
                        <hr>

                        <p>
                                <span class='quiet'>posted by Hank </span><% %>
                                <small>at <%= post.created_at.strftime(" %b, %Y %I:%M %p") %></small>
                        </p>
                                <small>
                                    <span>
                                    <%= link_to "#{post.comments.size} comments", post_path(post) %>
                                    </span>
                                </small>
                </div>
        </div>
<% end %>

app/views/posts/new.html.erb
<h4>New Oracle Retail Posts</h4>

<%= render 'form' %>

app/views/posts/show.html.erb
 <h4>Show Oracle Retail Posts</h4>

    <%= @post.id %><hr>

<p>
    <%= @post.title %><hr>
    <%= @post.description %><br>
</p>

<%= form_for [@post, @comment] do |f| %>
    <%= render 'shared/errors', obj: @comment %>

<div class= ‘control-group'>
    <%= f.label :body, 'Leave a comment' %>
    <%= f.text_area :body, rows: 8, class: 'span4'%>
</div>
    <%= f.submit "Create comment", class: "btn btn-primary" %>
<% end %><br><br>


<% @post.comments.each do |comment| %>

<div class = 'well span8' >
    <em>"<%= comment.body %>"<em>
</div>

<% end %>

app/views/shared/_errors.html.erb
<%= form_for obj do |f| %>
  <% if obj.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(obj.errors.count, "error") %> found:</h2>
      <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<p>
Logic Information Systems, Inc All rights reserved<br>
Copyright 2013

</p>